[language-server.typos]
command = "typos-lsp"

[language-server.efm]
command = "efm-langserver"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.vuels.config]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/Users/andy/.local/share/mise/installs/npm-vue-language-server/latest/lib/node_modules/@vue/language-server"
languages = ["vue"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/Users/andyfreeland/.local/share/mise/installs/npm-vue-language-server/latest/lib/node_modules/@vue/language-server"
languages = ["vue"]

[language-server.tofu-ls]
command = "tofu-ls"
args = ["serve"]

[[language]]
name = "python"
auto-format = true
language-servers = [
  { name = "ty", except-features = ["format"] },
  { name = "efm", only-features = ["diagnostics", "format"] },
  "typos",
]

[[language]]
name = "hcl"
auto-format = true
language-servers = [
  "tofu-ls",
  "typos",
]

[[language]]
name = "vue"
auto-format = false
language-servers = [
  { name = "vuels", except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
auto-format = false
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "vscode-eslint-language-server",
]

[[language]]
name = "javascript"
auto-format = false
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "vscode-eslint-language-server",
]

[[language]]
name = "json"
auto-format = false

[[language]]
name = "toml"
language-servers = [
  "tombi",
  "typos",
]

[[language]]
name = "git-commit"
language-servers = [
  "typos",
]

[[language]]
name = "markdown"
language-servers = [
  "typos",
]

[[language]]
name = "rst"
language-servers = [
  "typos",
]

[[language]]
name = "scss"
auto-format = false
